### ISSUE TITLE
Bump version requirement for x11-libs/libXft-bgra-patch

### ISSUE THREAD

**Issue by BSGalvan** [SabbathHex/nitratesky#12]
The ebuild for x11-libs/libXft-bgra-patch requires "=x11-libs/libXft-2.3.3-r0".
However, x11-libs/libXft-2.3.4 is [now stable](https://packages.gentoo.org/packages/x11-libs/libXft) (as of writing this) on amd64 in the Gentoo repos.

From my poking around in the [libXft-2.3.4 commit](https://gitlab.freedesktop.org/xorg/lib/libxft/-/commit/98b121f22c3477b508dd17aa5db99f2ebf36ade4), it seems that it is a minor patch update, so bumping up the ebuild requirement shouldn't be an issue.

**Comment by VTimofeenko** [comment]
Hi! Thanks for bringing this up. I will take a look at it this week.

**Comment by VTimofeenko** [comment]
@BSGalvan, had a surprise opening in the morning, was able to write it fairly quickly. Works good on my machine, `st` linked to libXft crashed without the patch and did not crash with it, displaying emoji.

Can you test and let me know?

**Comment by BSGalvan** [comment]
Thanks for the quick fix!
I tested it on my end and saw similar behaviour to what you described (`dmenu`/`dwm` crash without the patch while displaying emoji, and do not crash with the patch applied).
I will leave it to you to close if this is sufficient.

**Comment by VTimofeenko** [comment]
Yeah. 3/3 (my main machine and VM, your scenarios) cases passed, let's treat it as closed :)
