### ISSUE TITLE
Invalid news item error: net-analyzer/zabbix

### ISSUE THREAD

**Issue by BSGalvan** [SabbathHex/nitratesky#16]
Currently on my system, net-analyzer/rabbix is not installed.
However, every time any emerge (or emerge-adjacent) command is run, the following error is echoed:

```
!!! Invalid news item: /var/lib/layman/nitratesky/metadata/news/2021-11-24-upcoming-zabbix-removal-from-this-overlay/2021-11-24-upcoming-zabbix-removal-from-this-overlay.en.txt
!!!   line 6: Display-If-Installed: net-analyzer/zabbix::nitratesky
```
Is there a bug in the news item or am I missing something obvious here?

**Comment by VTimofeenko** [comment]
Hm. I think I thought that to better qualify the installed package, I could add the overlay name as usually works. Thanks for the report, I'll fix that.
