### ISSUE TITLE
Unavailable repository 'nest'

### ISSUE THREAD

**Issue by 69keks** [SabbathHex/nitratesky#17]
Hey, I installed your overlay from `eselect repository` but on using portage, every time I am getting a (hopefully harmless) message saying
``Unavailable repository 'nest' referenced by masters entry in '/var/db/repos/nitratesky/metadata/layout.conf'``

My question is -
Can I remove the repo name `nest` from the layout.conf file without causing any repercussions?

Or is it a problem on my side and the repo nest actually exists?

What can I do to solve this?
Thanks in advance.

**Comment by VTimofeenko** [comment]
Hi! The message is completely harmless :) This message means that my overlay ("nitratesky") has some packages that depend on packages in a different overlay ("nest" in this case) and that overlay is not enabled on your machine.

Looking through my packages, looks like it's `app-text/confluence_poster` that depends on package `dev-python/tomlkit` from `nest`)

Do feel free to remove nest from metadata file, but an update to my overlay will overwrite your local change. As an alternative, you could run `eselect repository enable nest`. If you don't want to install anything from that repository - you can mask all packages from `nest` by adding line `*/*::nest` to your `package.mask`.

**Comment by 69keks** [comment]
Oh, alright. Thank you for the clarification. I'm new to gentoo so I didn't quite understand what portage meant by that message and also I couldn't find anything specifically related to that on Google. I will enable the repo `nest` as I believe that would be the safest choice rather than running into a warning or error later when I need something from there. Good day!

**Comment by VTimofeenko** [comment]
You're welcome! 

> I will enable the repo nest as I believe that would be the safest choice rather than running into a warning or error later when I need something from there.

Packages from overlay typically take precedence over packages in base repo (if you want to install `app-misc/foo`. and it is present in both `::gentoo` and `::foo-overlay`, the latter will be installed). Do consider masking all packages from `::nest` overlay. As a rule of thumb, when I enable an overlay, I mask all packages and manually unmask ones that I want to be installed.

**Comment by 69keks** [comment]
Oh cool, guess I have a long way to go in gentoo. Thank you for the tip!

**Comment by VTimofeenko** [comment]
Gentoo is tons of fun to learn :) If you need help - feel free to drop me a line at ***@***.***
